### ISSUE TITLE
Wear OS 3 设备闪退

### ISSUE THREAD

**Issue by yen-soo** [windycn/miju#3]
Wear OS 3 的三星 Watch4，疯狂弹窗该应用专为旧版安卓打造之后闪退

**Comment by windycn** [comment]
可能是不太支持吧，需要手表至少支持webview或者一些相关原生库，或者是我版本调的太低，我改天升级一下底层API版本，请问你这个设备安卓底层是多少？

**Comment by reinyourheart02** [comment]
我在wear OS3的装置上无法启动，没有发生闪退的状况。wear OS3为Android 11底层。请开发大大解决下，谢谢！
