### ISSUE TITLE
问个敏感话题这项目是寄了吗？

### ISSUE THREAD

**Issue by laksg2009** [windycn/miju#4]
这项目是寄了吗？这项目是寄了吗？
没看到更新了。。。。。。。。。。。

最近刚入手oppo watch 2，你持续更新的话我就发酷安上。
如果不更新了我就不发了。

**Comment by windycn** [comment]
最近在忙，还没顾得上更新，我暑假一定更新，但是现在版本还能用啊

**Comment by laksg2009** [comment]
功能不多哈哈，目前不能控制我插座开关嘻嘻。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月9日(周二) 下午5:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [windycn/miju]问个敏感话题这项目是寄了吗？




 
最近在忙，还没顾得上更新，我暑假一定更新，但是现在版本还能用啊

**Comment by windycn** [comment]
> 功能不多哈哈，目前不能控制我插座开关嘻嘻。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年5月9日(周二) 下午5:11 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [windycn/miju]问个敏感话题这项目是寄了吗？ 最近在忙，还没顾得上更新，我暑假一定更新，但是现在版本还能用啊 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
现在最新版可以了，欢迎使用

**Comment by laksg2009** [comment]
等下试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月2日(周六) 上午9:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [windycn/miju] 问个敏感话题这项目是寄了吗？ (Issue #4)




  
功能不多哈哈，目前不能控制我插座开关嘻嘻。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年5月9日(周二) 下午5:11 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [windycn/miju]问个敏感话题这项目是寄了吗？ 最近在忙，还没顾得上更新，我暑假一定更新，但是现在版本还能用啊 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
 现在最新版可以了，欢迎使用
